### ISSUE TITLE
Access is denied. at SharpDX

### ISSUE THREAD

**Issue by ticktostick** [Jay-Rad/Remotely#361]
**Describe the bug**
I want to remote control a windows 10 virtual machine on vmware ESX .  when I am connected to machine with remote desktop and try to  remotely control the machine with Remotely I get only a black screen and noting happens
but if I sign out from my remote desktop session . and connect again with Remotely it works without problem
I can select remote desktop session from interface but again noting happens only a black screen 

**To Reproduce**
1. Go to Home
2. Click on Actions-->Remote control

**Remotely Version**
Server : 2021.08.26.1335 (installed on ubuntu)
Agent : 2021.08.26.1335 (on windows 10 pro 21H1)

**Expected Behavior**
show the remote controlled machine desktop

**Desktop (please complete the following information):**
 - OS: windows 10 pro  21H1
 - Browser :chrome
 - Version : 94.0.4606.81

**Additional Context**

LOG when not connected with remote desktop and works OK

[Error]	[InitDirectX]	HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.
	   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.Output1.DuplicateOutput(IUnknown deviceRef)
   at Remotely.Desktop.Win.Services.ScreenCapturerWin.InitDirectX() in D:\a\1\s\Desktop.Win\Services\ScreenCapturerWin.cs:line 368	SharpDX

LOG when I am remote desktop and trying to remote control:

[Error]	[InitDirectX]	HRESULT: [0x80070005], Module: [General], ApiCode: [E_ACCESSDENIED/General access denied error], Message: Access is denied.
	   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.Output1.DuplicateOutput(IUnknown deviceRef)
   at Remotely.Desktop.Win.Services.ScreenCapturerWin.InitDirectX() in D:\a\1\s\Desktop.Win\Services\ScreenCapturerWin.cs:line 368	SharpDX
[Error]	[GetBitBltFrame]	The handle is invalid.	   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize)

**Comment by ticktostick** [comment]
checked its ok when not minimized. its ok for me 
if not a bug we can close it 
Thank you
