### ISSUE TITLE
Remotely_Server_Installer Unhandled Exception after successful build

### ISSUE THREAD

**Issue by develpudu** [Jay-Rad/Remotely#379]
**Describe the bug**

I have the same error #276 but with the lastest release

After successfully finishishing the build action on github the script stops with an unhandled exception

```
Directory: /var/www/remotely/

Get artifacts response status code: OK

Trigger GitHub Actions build.

Dispatch response status code: NoContent

Build action triggered successfully.  Waiting for build
completion.

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Downloading build artifact.

Download artifact response status code: OK

Extracting files.

Launching install script for selected reverse proxy type.

Unhandled exception. System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName, String arguments)
   at Server.Installer.Services.ServerInstaller.LaunchExternalInstaller(CliParams cliParams)
   at Server.Installer.Services.ServerInstaller.PerformInstall(CliParams cliParams)
   at Server.Installer.Program.Main(String[] args)
   at Server.Installer.Program.<Main>(String[] args)
Aborted

```
**To Reproduce**

Tested on Ubuntu 20.04

- execute ./Remote_Server_Installer
- Make sure to select true when asked for new build
- wait for the build to be done
- See error

**Remotely Version**
Server: Current release v2021.08.26.1335

**Expected Behavior**

Fully execute the setup procedure

**Comment by tobias-dietz** [comment]
I had the same problem on CentOS 8 (LXC). Installing `sudo` solved the issue because `ServerInstaller.cs` requires `sudo`:

https://github.com/immense/Remotely/blob/eee74139bee8da3e5d55e084b8a70e26a2d85d5a/Server.Installer/Services/ServerInstaller.cs#L165

**Comment by develpudu** [comment]
no need of sudo if executed by root
