### ISSUE TITLE
Unattended access computer reports to be offline

### ISSUE THREAD

**Issue by kr4ft3r** [Jay-Rad/Remotely#93]
I'm using the v2020.03.19.0115 Release.
Desktop agent works great, but I'm having no luck with unattended access.
Server is on a clean install of Ubuntu 18.04
Client device is Windows 10 with no antivirus. After installing the resident agent (downloaded from server website), the device appears on the grid but reports to be offline. Uninstalling and reinstalling the resident agent just adds duplicate offline device to the grid (btw is there a way to delete devices from the list?).

This is an example of what is periodically repeated in the logs, from the moment the resident agent is installed:

```
2020-03-20 16:16:35.003	[INFO]	Websocket closed.  Reconnecting in 29 seconds...
2020-03-20 16:17:06.085	[ERROR]	A task was canceled.	   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter`1.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.InvokeCoreAsync[TResult](HubConnection hubConnection, String methodName, Object[] args, CancellationToken cancellationToken)
   at Remotely.Agent.Services.DeviceSocket.Connect() in C:\Build\_work\1\s\Agent\Services\DeviceSocket.cs:line 61
   at Remotely.Agent.Program.HandleConnection() in C:\Build\_work\1\s\Agent\Program.cs:line 90	System.Private.CoreLib
2020-03-20 16:17:07.555	[INFO]	Websocket closed.  Reconnecting in 12 seconds...
```

**Comment by Jay-Rad** [comment]
Yeah, I made a silly mistake and broke something on that build.  It's fixed in the latest build.
